### ISSUE TITLE
Fix deployment again

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#947]
The build is failing at Heroku. What's up?

![screen shot 2016-12-20 at 5 29 25 pm](https://cloud.githubusercontent.com/assets/134455/21370488/e9e37a70-c6d9-11e6-8015-f73f3f2e2f99.png)

**Comment by whit537** [comment]
```
-----> Python app detected
     $ pip install -r requirements.txt
       Obtaining file:///tmp/build_43624b206fad8e5a633cc1acbe71d3e7 (from -r /tmp/build_43624b206fad8e5a633cc1acbe71d3e7/requirements.txt (line 22))
       Installing collected packages: inside-gratipay
         Found existing installation: inside-gratipay 0.0.0
       Exception:
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
           status = self.run(options, args)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
           prefix=options.prefix_path,
         File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
           requirement.uninstall(auto_confirm=True)
         File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 703, in uninstall
           '(at %s)' % (link_pointer, self.name, dist.location)
       AssertionError: Egg-link /app does not match installed location of inside-gratipay (at /tmp/build_43624b206fad8e5a633cc1acbe71d3e7)
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by whit537** [comment]
https://github.com/pypa/pip/issues/3784
https://github.com/pypa/pip/issues/640

**Comment by whit537** [comment]
@kennethreitz Is it perhaps obvious to you what is going on here?

**Comment by kennethreitz** [comment]
This may be a bug on our end. I will be investigating tomorrow. @whit537 want to hop on a call with me?

**Comment by kennethreitz** [comment]
I believe I fixed this issue today. I hate to ask this, but can you try again now?

**Comment by kennethreitz** [comment]
or was that deploy from 3 hours ago?

**Comment by whit537** [comment]
Just got off the phone w/ @kennethreitz ... we are back on track! Thanks, Kenneth! 💃 🙇

The issue was https://github.com/heroku/heroku-buildpack-python/issues/347. @kennethreitz helped purge our build cache and then another push and we were set. 👍
